# Generated by Django 5.0.1 on 2024-01-14 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu_pages', '0002_category_serviceblock'),
        ('menu_pages', '0003_alter_contactus_message'),
    ]

    operations = [
    ]
