# Generated by Django 5.0.1 on 2024-01-15 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_pages', '0004_merge_20240114_1144'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'Feedback', 'verbose_name_plural': 'Feedback'},
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': 'Menu', 'verbose_name_plural': 'Menu'},
        ),
        migrations.AlterModelOptions(
            name='serviceblock',
            options={'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.AddField(
            model_name='category',
            name='category_fi',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='category_ru',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='contactus',
            name='email_fi',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='contactus',
            name='email_ru',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='contactus',
            name='message_fi',
            field=models.TextField(null=True, verbose_name='Сообщение'),
        ),
        migrations.AddField(
            model_name='contactus',
            name='message_ru',
            field=models.TextField(null=True, verbose_name='Сообщение'),
        ),
        migrations.AddField(
            model_name='contactus',
            name='name_fi',
            field=models.CharField(max_length=50, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='contactus',
            name='name_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='menu',
            name='title_fi',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='title_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='url_fi',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='url_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='serviceblock',
            name='category_fi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='menu_pages.category'),
        ),
        migrations.AddField(
            model_name='serviceblock',
            name='category_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='menu_pages.category'),
        ),
        migrations.AddField(
            model_name='serviceblock',
            name='service_fi',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='serviceblock',
            name='service_ru',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='message',
            field=models.TextField(verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
    ]
