# Generated by Django 4.2.7 on 2024-01-17 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_pages', '0005_alter_category_options_alter_contactus_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceblock',
            name='service',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='serviceblock',
            name='service_fi',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='serviceblock',
            name='service_ru',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
