# Generated by Django 4.2.7 on 2024-01-18 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_pages', '0006_alter_serviceblock_service_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_fi',
        ),
        migrations.RemoveField(
            model_name='category',
            name='category_ru',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='email_fi',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='email_ru',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='message_fi',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='message_ru',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='name_fi',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='title_fi',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='url_fi',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='url_ru',
        ),
        migrations.RemoveField(
            model_name='serviceblock',
            name='category_fi',
        ),
        migrations.RemoveField(
            model_name='serviceblock',
            name='category_ru',
        ),
        migrations.RemoveField(
            model_name='serviceblock',
            name='service_fi',
        ),
        migrations.RemoveField(
            model_name='serviceblock',
            name='service_ru',
        ),
        migrations.AlterField(
            model_name='contactus',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
