# Generated by Django 4.2.7 on 2024-01-18 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu_pages', '0007_remove_category_category_fi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_fi',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='category_ru',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='contactus',
            name='email_fi',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='contactus',
            name='email_ru',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='contactus',
            name='message_fi',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='contactus',
            name='message_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='contactus',
            name='name_fi',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contactus',
            name='name_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='title_fi',
            field=models.CharField(max_length=50, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='menu',
            name='title_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='menu',
            name='url_fi',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='url_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='serviceblock',
            name='category_fi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='menu_pages.category'),
        ),
        migrations.AddField(
            model_name='serviceblock',
            name='category_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='menu_pages.category'),
        ),
        migrations.AddField(
            model_name='serviceblock',
            name='service_fi',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='serviceblock',
            name='service_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Title'),
        ),
    ]
