# Generated by Django 4.2.7 on 2024-01-18 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu_pages', '0008_category_category_fi_category_category_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_fi',
        ),
        migrations.RemoveField(
            model_name='category',
            name='category_ru',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='email_fi',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='email_ru',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='message_fi',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='message_ru',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='name_fi',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='title_fi',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='url_fi',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='url_ru',
        ),
        migrations.RemoveField(
            model_name='serviceblock',
            name='category_fi',
        ),
        migrations.RemoveField(
            model_name='serviceblock',
            name='category_ru',
        ),
        migrations.RemoveField(
            model_name='serviceblock',
            name='service_fi',
        ),
        migrations.RemoveField(
            model_name='serviceblock',
            name='service_ru',
        ),
    ]
