# Generated by Django 4.2.7 on 2024-01-18 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu_pages', '0010_delete_serviceblock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
