# Generated by Django 4.2.7 on 2024-01-18 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu_pages', '0013_category_category_fi_category_category_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='url_fi',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='url_ru',
        ),
    ]
