# Generated by Django 4.2.7 on 2024-01-19 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_pages', '0014_remove_menu_url_fi_remove_menu_url_ru'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='url_fi',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='url_ru',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
