# Generated by Django 4.2.7 on 2024-01-19 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu_pages', '0015_menu_url_fi_menu_url_ru'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='url_fi',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='url_ru',
        ),
    ]
