# Generated by Django 4.2.7 on 2024-01-20 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_pages', '0017_alter_contactus_email_alter_contactus_email_fi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='email_fi',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='email_ru',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='message_fi',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='message_ru',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='name_fi',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='name_ru',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
