# Generated by Django 4.2.7 on 2024-01-20 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu_pages', '0018_alter_contactus_email_alter_contactus_email_fi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='email_fi',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='email_ru',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='message_fi',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='message_ru',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='name_fi',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='name_ru',
        ),
    ]
