# Generated by Django 5.0b1 on 2024-01-23 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu_pages', '0005_price_alter_category_options_alter_contactus_options_and_more'),
        ('menu_pages', '0019_remove_contactus_email_fi_remove_contactus_email_ru_and_more'),
    ]

    operations = [
    ]
