# Generated by Django 5.0b1 on 2024-01-23 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_pages', '0020_merge_20240123_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='title_fi',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='price',
            name='title_ru',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
