# Generated by Django 4.2.7 on 2024-01-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_pages', '0021_price_title_fi_price_title_ru'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='email_fi',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='contactus',
            name='email_ru',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='contactus',
            name='message_fi',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='contactus',
            name='message_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='contactus',
            name='name_fi',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contactus',
            name='name_ru',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
